const express=require("express")
const { userSignup, userLogin, sendMailResetPassword, resetPassword, updateProfile, aboutProfile, addNewAddress, addressList, deleteAddress } = require("../../../controllers/User_PanelControllers/userControllers/userControllers")
const { signupValidation } = require("../../../validation/userValidation")
const router=express.Router()
const tokenAuthorisationUser=require("../../../middleware/userAuth")
const { uploads } = require("../../../middleware/imageStorage")
const imageStorage = require("../../../middleware/imageStorage")

router.post("/signup",signupValidation,userSignup)
router.post("/login",userLogin)
router.post("/send-mail",sendMailResetPassword)
router.post("/reset-password/:id/:token",resetPassword)
router.post("/edit-profile/:id",updateProfile)
router.post("/about-profile/:id",imageStorage,aboutProfile)
router.post("/add-address",addNewAddress)
router.post("/list-address",addressList)
router.delete("/delete-address/:id",deleteAddress)
module.exports=router