const express=require("express")
const router=express.Router()
const user=require("./adminRoutes/userRoutes")
const category=require("./categoryRoutes/commonRoutes")
const product=require("./categoryRoutes/productRoutes")
const order=require("./orderRoutes/commonRoutes")
const dashboards=require("./dashboardRoutes/commonRoutes")
const reporter=require("./reporterRoutes/commonRoutes")
const announcement=require("./announcementRoutes/commonRoutes")
const notification=require("./notificationRoutes/commonRoutes")
const staff=require("./staffRoutes/commonRoutes")
const homeScreen=require("./homeScreenRoutes/commonRoutes")
const content=require("./contentRoutes/commonRoutes")
const contact=require("./contactRoutes/commonRoutes")
const thougth=require("./thougthRoutes/commonRoutes")
const help=require("./helpRoutes/commonRoutes")

router.use("/user",user)
router.use("/category",category)
router.use("/product",product)
router.use("/order",order)
router.use("/dashboards",dashboards)
router.use("/reporter",reporter)
router.use("/announcement",announcement)
router.use("/notification",notification)
router.use("/staff",staff)
router.use("/home",homeScreen)
router.use("/content",content)
router.use("/contact",contact)
router.use("/thougth",thougth)
router.use("/help",help)
module.exports=router