const express=require("express")
const router=express.Router()
const valuesControllers=require("../../controllers/categoryManagement/valuesControllers")
const authentication=require("../../middleware/userAuth")

router.post("/createValues",authentication,valuesControllers.createValues)
router.post("/valuesList",authentication,valuesControllers.valuesList)
router.patch("/valuesUpdate/:id",authentication,valuesControllers.valuesUpdate)
router.post("/valuesSearch",authentication,valuesControllers.valuesSearch)
router.post("/selectCategory",authentication,valuesControllers.selectCategory)
router.post("/selectSubCategory",authentication,valuesControllers.selectSubCategory)
router.post("/selectSubSubCategory",authentication,valuesControllers.selectSubSubCategory)
router.post("/selectAttribute",authentication,valuesControllers.selectAttribute)
router.patch("/checkStatus/:id",authentication,valuesControllers.checkStatus)
module.exports=router