const express=require("express")
const router=express.Router()
const valuesControllers=require("../../controllers/categoryManagement/valuesControllers")
const tokenAuthorisationUser = require("../../middleware/userAuth")

router.post("/createValues",tokenAuthorisationUser,valuesControllers.createValues)
router.post("/valuesList",tokenAuthorisationUser,valuesControllers.valuesList)
router.patch("/valuesUpdate/:id",tokenAuthorisationUser,valuesControllers.valuesUpdate)
router.post("/valuesSearch",tokenAuthorisationUser,valuesControllers.valuesSearch)
router.post("/selectCategory",tokenAuthorisationUser,valuesControllers.selectCategory)
router.post("/selectSubCategory",tokenAuthorisationUser,valuesControllers.selectSubCategory)
router.post("/selectSubSubCategory",tokenAuthorisationUser,valuesControllers.selectSubSubCategory)
router.post("/selectAttribute",tokenAuthorisationUser,valuesControllers.selectAttribute)
router.patch("/checkStatus/:id",tokenAuthorisationUser,valuesControllers.checkStatus)
module.exports=router